apiVersion: apps/v1
kind: Deployment
metadata:
  name: fonomed-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fonomed-backend
  template:
    metadata:
      labels:
        app: fonomed-backend
    spec:
      containers:
        - name: fonomed-backend
          image: fonomed-backend:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: production
            - name: DB_HOST
              value: postgres-service
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: fonomed_db
            - name: DB_USER
              value: admin
            - name: DB_PASSWORD
              value: secret
